<a href="https://colab.research.google.com/github/sahala-mol/ds-ml/blob/main/sahala_mol_vs_Na%C3%AFve_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aim**: Program to implement Naïve Bayes Algorithm using any standard dataset
available in the public domain and find the accuracy of the algorithm

# **Short notes: Naive Bayes**

Bayes’ Theorem provides a way that we can calculate the probability of a piece of data belonging to a given class, given our prior knowledge. Bayes’ Theorem is stated as:

#      P(class|data) = (P(data|class) * P(class)) / P(data)  

Where P(class|data) is the probability of class given the provided data.

We are using Iris Dataset. The Iris Flower Dataset involves predicting the flower species given measurements of iris flowers.

It is a multiclass classification problem. The number of observations for each class is balanced. There are 150 observations with 4 input variables and 1 output variable. The variable names are as follows:

  Sepal length in cm.

  Sepal width in cm.

  Petal length in cm.

  Petal width in cm.

Class.

**Algorithm**:

Step 1: Separate By Class.

Step 2: Summarize Dataset.

Step 3: Summarize Data By Class.

Step 4: Gaussian Probability Density Function.

Step 5: Class Probabilities.

In [11]:
#Import Modules
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
#Load iris dataset & do train_test_split
iris = pd.read_csv('/content/Iris (1).csv')
iris.head()
x=iris.drop(['Species','Id'],axis=1)
y=iris['Species']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42,stratify=y)
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In this step, we introduce the class GaussianNB that is used from the sklearn.naive_bayes library. Here, we have used a Gaussian model, there are several other models such as Bernoulli, Categorical and Multinomial. Here, we assign the GaussianNB class to the variable classifier and fit the X_train and y_train values to it for training purpose.

In [14]:
#Implement Naive Bayes
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)




GaussianNB()

In [15]:
#Predict the values for test data
y_pred = classifier.predict(x_test)
y_pred

# Display accuracy score & display confusion matrix & classification report
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



0.9111111111111111
[[15  0  0]
 [ 0 14  1]
 [ 0  3 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.82      0.93      0.87        15
 Iris-virginica       0.92      0.80      0.86        15

       accuracy                           0.91        45
      macro avg       0.92      0.91      0.91        45
   weighted avg       0.92      0.91      0.91        45



From the above confusion matrix, we infer that, out of 45 test set data, 44 were correctly classified and only 1 was incorrectly classified. This gives us a high accuracy of 97.7%.